# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c3fe0f7d628642aab16e752397d41fc841fb9c6fb64f9f6d1e2a0542a3380a089c391fff06f4187feea60086ea40d29f524e46def75d829c37e4a0e63091006

test:
  secret_key_base: 46b2451793c3921fb55485299fc6b5fdee0fac6c809c052c80957672d0c1552af72c80bef11044ab401c844974354d9ce9c19240390a8ddddd30d66acddc7c0b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
